import type { LessonTemplate } from '../types';

export const BUILTIN_TEMPLATES: LessonTemplate[] = [
  {
    id: 'template-intro-lesson',
    name: 'Introduction Lesson',
    description: 'A structured template for introducing a new topic to students.',
    subject: 'General',
    duration: 60,
    objectives: [
      'Students will be introduced to [topic]',
      'Students will identify key vocabulary related to [topic]',
    ],
    success_criteria: [
      'All students can name at least 3 key terms',
      'Most students can explain the basic concept in their own words',
    ],
    activities: [
      {
        name: 'Starter/Hook Activity',
        planned_duration: 10,
        notes: 'Engage students with a question or image related to the topic',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Direct Teaching / Explanation',
        planned_duration: 15,
        notes: 'Present new material clearly using visuals and examples',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Guided Practice',
        planned_duration: 15,
        notes: 'Work through examples together as a class',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Independent/Group Task',
        planned_duration: 15,
        notes: 'Students practise with teacher circulating',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Plenary / Reflection',
        planned_duration: 5,
        notes: 'Review learning objectives and recap key points',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
    ],
    differentiation: {
      eal: {
        strategies_used: ['Visual aids & images', 'Key vocabulary pre-teaching'],
        vocabulary_introduced: [],
        student_understanding_level: '',
        notes: '',
      },
      sen: {
        accommodations_used: ['Chunked instructions', 'Visual timetable'],
        behaviour_notes: '',
        engagement_notes: '',
        progress_notes: '',
      },
      gifted_extension: ['Research deeper aspects of [topic]', 'Create a presentation for the class'],
    },
    resources: ['Whiteboard', 'Printed worksheets'],
    is_builtin: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'template-literacy',
    name: 'Literacy / Reading Lesson',
    description: 'For English or literacy-focused lessons involving reading comprehension.',
    subject: 'English',
    duration: 60,
    objectives: [
      'Students will read and analyse [text/passage]',
      'Students will identify key language features',
      'Students will respond to comprehension questions',
    ],
    success_criteria: [
      'All students can answer retrieval questions',
      'Most students can identify author techniques',
      'Some students can evaluate the effectiveness of language choices',
    ],
    activities: [
      {
        name: 'Reading Warm-Up',
        planned_duration: 5,
        notes: 'Recap previous lesson or introduce new text context',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Shared Reading',
        planned_duration: 15,
        notes: 'Read text aloud, pausing for discussion',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Vocabulary Exploration',
        planned_duration: 10,
        notes: 'Identify and discuss key vocabulary',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Comprehension Task',
        planned_duration: 20,
        notes: 'Students answer questions independently',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Share & Review',
        planned_duration: 10,
        notes: 'Share answers, peer assessment',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
    ],
    differentiation: {
      eal: {
        strategies_used: ['Key vocabulary pre-teaching', 'Bilingual glossary', 'Simplified instructions'],
        vocabulary_introduced: [],
        student_understanding_level: '',
        notes: '',
      },
      sen: {
        accommodations_used: ['Enlarged text', 'Scribe/reader support', 'Reduced workload'],
        behaviour_notes: '',
        engagement_notes: '',
        progress_notes: '',
      },
      gifted_extension: ['Analytical essay paragraph', 'Compare to another text'],
    },
    resources: ['Printed text extract', 'Comprehension worksheet', 'Dictionary'],
    is_builtin: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'template-maths',
    name: 'Maths Skills Lesson',
    description: 'Structured lesson for teaching a new maths skill or concept.',
    subject: 'Mathematics',
    duration: 55,
    objectives: [
      'Students will understand how to [skill]',
      'Students will practise [skill] with increasing complexity',
    ],
    success_criteria: [
      'All students can complete basic practice questions',
      'Most students can apply the skill to word problems',
      'Some students can solve multi-step problems',
    ],
    activities: [
      {
        name: 'Arithmetic Warm-Up',
        planned_duration: 5,
        notes: 'Mental maths or recap questions',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Concept Introduction',
        planned_duration: 10,
        notes: 'Introduce the new concept with worked examples',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Guided Practice (We Do)',
        planned_duration: 10,
        notes: 'Teacher models, students follow along',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Independent Practice',
        planned_duration: 25,
        notes: 'Tiered worksheets: bronze/silver/gold',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
      {
        name: 'Exit Ticket',
        planned_duration: 5,
        notes: 'Quick assessment question to check understanding',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
    ],
    differentiation: {
      eal: {
        strategies_used: ['Visual aids & images', 'Graphic organisers'],
        vocabulary_introduced: [],
        student_understanding_level: '',
        notes: '',
      },
      sen: {
        accommodations_used: ['Differentiated worksheets', 'Extra time', 'Preferential seating'],
        behaviour_notes: '',
        engagement_notes: '',
        progress_notes: '',
      },
      gifted_extension: ['Investigate a related mathematical proof', 'Create their own word problems'],
    },
    resources: ['Textbook', 'Calculator (if appropriate)', 'Mini whiteboards'],
    is_builtin: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'template-quick-reflection',
    name: 'Quick Reflection',
    description: 'Minimal 1-minute reflection template for busy teachers.',
    subject: 'General',
    duration: 60,
    objectives: [''],
    success_criteria: [''],
    activities: [
      {
        name: 'Main Activity',
        planned_duration: 60,
        notes: '',
        students_understood: false,
        students_struggled: false,
        completed: false,
      },
    ],
    differentiation: {
      eal: {
        strategies_used: [],
        vocabulary_introduced: [],
        student_understanding_level: '',
        notes: '',
      },
      sen: {
        accommodations_used: [],
        behaviour_notes: '',
        engagement_notes: '',
        progress_notes: '',
      },
      gifted_extension: [],
    },
    resources: [],
    is_builtin: true,
    created_at: new Date().toISOString(),
  },
];
